const fs = require('fs');
const path = require('path');

// locales 폴더의 JSON 파일들을 읽어서 i18n.js 업데이트
function main() {
    console.log('🔄 Updating i18n.js from locale files...\n');

    const localesDir = path.join(__dirname, '../locales');
    const i18nPath = path.join(__dirname, '../public/js/i18n.js');

    // 모든 언어 파일 읽기
    const languages = ['en', 'ko', 'ja', 'es', 'zh-TW', 'vi'];
    const translations = {};

    for (const lang of languages) {
        const filePath = path.join(localesDir, `${lang}.json`);
        if (fs.existsSync(filePath)) {
            translations[lang] = JSON.parse(fs.readFileSync(filePath, 'utf8'));
            console.log(`✅ Loaded ${lang}.json`);
        } else {
            console.warn(`⚠️  ${lang}.json not found, skipping...`);
        }
    }

    // i18n.js 파일 생성
    let i18nContent = `// Auto-generated by update-i18n.js
// To update translations: 
// 1. Edit files in /locales folder
// 2. Run: npm run update-i18n

const translations = ${JSON.stringify(translations, null, 4).replace(/"([^"]+)":/g, '$1:')};

// 현재 언어 (기본값: 영어)
let currentLang = localStorage.getItem('tikfind_lang') || 'en';

// 브라우저 언어 자동 감지
function detectBrowserLanguage() {
    const browserLang = navigator.language || navigator.userLanguage;
    
    if (browserLang.startsWith('ko')) return 'ko';
    if (browserLang.startsWith('ja')) return 'ja';
    if (browserLang.startsWith('es')) return 'es';
    if (browserLang.startsWith('zh')) return 'zh-TW';
    if (browserLang.startsWith('vi')) return 'vi';
    
    return 'en';
}

// IP 기반 국가 감지 (선택사항)
async function detectCountryByIP() {
    try {
        const response = await fetch('https://ipapi.co/json/');
        const data = await response.json();
        const countryCode = data.country_code;
        
        // 국가 코드를 언어 코드로 매핑
        const countryToLang = {
            'KR': 'ko',
            'JP': 'ja',
            'ES': 'es',
            'MX': 'es',
            'AR': 'es',
            'TW': 'zh-TW',
            'HK': 'zh-TW',
            'VN': 'vi'
        };
        
        return countryToLang[countryCode] || 'en';
    } catch (error) {
        console.log('IP detection failed, using browser language');
        return detectBrowserLanguage();
    }
}

// 언어 초기화 (IP 기반 우선, 그 다음 브라우저 언어)
if (!localStorage.getItem('tikfind_lang')) {
    detectCountryByIP().then(lang => {
        currentLang = lang;
        localStorage.setItem('tikfind_lang', lang);
        applyTranslations();
    });
} else {
    currentLang = localStorage.getItem('tikfind_lang');
}

// 번역 함수
function t(key) {
    return translations[currentLang]?.[key] || translations['en']?.[key] || key;
}

// 언어 변경
function changeLanguage(lang) {
    if (translations[lang]) {
        currentLang = lang;
        localStorage.setItem('tikfind_lang', lang);
        location.reload();
    }
}

// 번역 적용
function applyTranslations() {
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        element.textContent = t(key);
    });
}

// 페이지 로드 시 번역 적용
document.addEventListener('DOMContentLoaded', function() {
    applyTranslations();
    createLanguageSelector();
});

// 언어 선택 드롭다운 생성
function createLanguageSelector() {
    const langSelector = document.getElementById('language-selector');
    if (!langSelector) return;
    
    const languages = {
        'en': 'English',
        'ko': '한국어',
        'ja': '日本語',
        'es': 'Español',
        'zh-TW': '繁體中文',
        'vi': 'Tiếng Việt'
    };
    
    let html = '<select id="lang-dropdown" class="px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 bg-white">';
    
    for (const [code, name] of Object.entries(languages)) {
        const selected = code === currentLang ? 'selected' : '';
        html += \`<option value="\${code}" \${selected}>\${name}</option>\`;
    }
    
    html += '</select>';
    langSelector.innerHTML = html;
    
    document.getElementById('lang-dropdown').addEventListener('change', function(e) {
        changeLanguage(e.target.value);
    });
}

// Export for use in other scripts
window.TikFindI18n = {
    t,
    changeLanguage,
    currentLang: () => currentLang
};
`;

    fs.writeFileSync(i18nPath, i18nContent, 'utf8');
    console.log('\n✅ i18n.js updated successfully!');
    console.log('📍 Location: public/js/i18n.js\n');
}

main();
